    import { fn } from '@storybook/test';
    import AwardCard from './AwardCard';

    export default {
        title: 'Example/AwardCard',
        component: AwardCard,
        parameters: {
            layout: 'centered', // Center the component in the Canvas
        },
        tags: ['autodocs'], // Autogenerated Autodocs entry
        argTypes: {
            backgroundColor: { control: 'color' }, // Control for backgroundColor prop
        },
        args: { onClick: fn() }, // Spy on the onClick arg for actions panel
    };

    export const loadedData = {
        args: {
            item: {
                id: 1,
                brandName: 'Horecah',
                title: 'Best Chef',
                department: 'Kitchen',
                position: 'Head Chef'
            }
        }
    };
